name: Aruco
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4  # ※これは macOS 専用なので、Windows では無視されます
  - asttokens=3.0.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cycler=0.11.0
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - freetype=2.13.3
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nest-asyncio=1.6.0
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openssl=3.0.16
  - parso=0.8.4
  - pexpect=4.9.0  # Windowsでは不要だが、問題なくスキップされます
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - ptyprocess=0.7.0  # Windowsでは不要、スキップされます
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.11.13
  - python_abi=3.11
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tk=8.6.14
  - traitlets=5.14.3
  - typing_extensions=4.14.0
  - tzdata=2025b
  - wcwidth=0.2.13
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.22.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - brotli==1.0.9
    - certifi==2025.4.26
    - contourpy==1.3.1
    - debugpy==1.8.11
    - fonttools==4.55.3
    - idna==3.7
    - kiwisolver==1.4.8
    - matplotlib==3.10.0
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - numpy==1.24.3
    - opencv-contrib-python==4.8.0.74
    - opencv-python==4.8.0.74
    - packaging==24.2
    - pillow==11.1.0
    - psutil==7.0.0
    - pyparsing==3.2.0
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pyzmq==24.0.1
    - requests==2.32.3
    - setuptools==78.1.1
    - six==1.17.0
    - tornado==6.5.1
    - unicodedata2==15.1.0
    - urllib3==2.3.0
    - wheel==0.45.1
